config/routes.rb
Langapp1::Application.routes.draw do
  resources :contentusers

  resources :games

  resources :scores

  devise_for :users

  resources :users

  resources :sentences

  resources :languages

  

  resources :categories do
    resources :words
    resources :sentences

    member do
      get 'test'
    end
    
  end
  
  
  

  root :to => 'categories#index'

end

app/models/word.rb
class Word < ActiveRecord::Base
  attr_accessible :language_id, :master_word_id, :word, :category_ids, :french, :spanish, :german, :mandarin, :russian, :arabic, :user_ids, :sentence

  belongs_to :language
  has_and_belongs_to_many :categories
  has_and_belongs_to_many :users
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  # GET /words
  # GET /words.json

  
  def index
    @category = Category.find(params[:category_id])
    @words = @category.words.where(:sentence => false)
    @sentences = @category.words.where(:sentence => true)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @words }
    end
  end

  # GET /words/1
  # GET /words/1.json
  def show
    @word = Word.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @word }
    end
  end

  # GET /words/new
  # GET /words/new.json
  def new
    @category = Category.find(params[:category_id])
    @word = @category.words.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @word }
    end
  end

  # GET /words/1/edit
  def edit
    @category = Category.find(params[:category_id])
    @word = @category.words.build
  end

  # POST /words
  # POST /words.json
  def create
    @category = Category.find(params[:category_id])
    @word = @category.words.build(params[:word])
      if @word.save
        flash[:notice] = "successfully saved word"
        redirect_to category_words_url(@category)
      else
        render :action => 'new'
      end

    
   
  end

  # PUT /words/1
  # PUT /words/1.json
  def update
    @category = Category.find(params[:category_id])
    @word = @category.words.build

    respond_to do |format|
      if @word.update_attributes(params[:word])
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word = Word.find(params[:id])
    @word.destroy

    respond_to do |format|
      format.html { redirect_to words_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/_form.html.erb
<%= form_for([@category,@word]) do |f| %>
<%= hidden_field_tag :category_id, params[:category_id] %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :word %><br>
    <%= f.text_field :word %>
  </div>

  <div class="field">
    <%= f.label :sentence %><br>
    <%= f.check_box :sentence %>
  </div>

  <div class="field">
    <%= f.label :spanish %><br>
    <%= f.text_field :spanish %>
  </div>

  <div class="field">
    <%= f.label :french %><br>
    <%= f.text_field :french %>
  </div>

  <div class="field">
    <%= f.label :german %><br>
    <%= f.text_field :german %>
  </div>
  


  <div class="field">
    <p class="large-font">Choose the categories associated with this word</p>
  <% for category in Category.all %>
      <label class="checkbox inline col-xs-2">
        <%= check_box_tag 'word[category_ids][]', category.id, @word.categories.include?(category) %>
        <%= link_to category.category, category_path(category) %>
      </label>
    <% end %>
  </div>
  <div class="clearfix"></div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<h1>Editing word</h1>

<%= render 'form' %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<div>
  <ul id="myTab" class="nav nav-tabs">
  <li class="active" ><a href="#generic" data-toggle="tab">Words</a></li>
  <li><a href="#custom" data-toggle="tab">Sentences</a></li>
</ul>
<div class="tab-content">
  <div class="tab-pane fade in active" id="generic">
  <h1>Words</h1>
  <table>
    <thead>
      <tr>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <hr>
      <% @words.each do |word| %>
          <tr class="show-text word-id-<%= word.id %> language-id-<%= word.language_id %>">
            <td class="word-no-<%= word.id %>">
              <%= word.word %></td>
            <td>
              <a href="#">
                <span id="dummy" onclick="playSound(this, 'assets/<%= word.word %>.wav');">
                  <span class="glyphicon glyphicon-play-circle">
                  </span>
                </span>
              </a>
            </td>
            <td>
              <a href="#">
                <span class="glyphicon glyphicon-plus-sign">
                </span>
              </a>
            </td>
            <td class="word-no-<%= word.id %>"><a href="#" class="translate"><span class="glyphicon glyphicon-refresh"></span></a></td>
          </tr>

          <tr class="hide-text word-id-<%= word.id %> language-id-<%= word.language_id %>">
            <td class="word-no-<%= word.id %>">
              <% lang = current_user.targettongue_id %>
              <% lang = Language.find(lang) %>
              <% lang = lang.language %>
              <%= link_to word.french, lang %>
            </td>
            <td><a href="#"><span class="glyphicon glyphicon-play-circle"></span></a></td>
            <td><a href="#"><span class="glyphicon glyphicon-plus-sign"></span></a></td>
            <td class="word-no-<%= word.id %>"><a href="#"><span class="glyphicon glyphicon-refresh"></span></a></td>
          </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to 'New Word', new_category_word_path(@category), class: 'btn btn-success' %>
  </div>
  <div class="tab-pane fade" id="custom">
      <h2>Sentences</h2>
      <table>
    <thead>
      <tr>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <hr>
      <% @sentences.each do |word| %>
          <tr class="show-text word-id-<%= word.id %> language-id-<%= word.language_id %>">
            <td class="word-no-<%= word.id %>">
              <%= word.word %></td>
            <td>
              <a href="#">
                <span id="dummy" onclick="playSound(this, 'assets/<%= word.word %>.wav');">
                  <span class="glyphicon glyphicon-play-circle">
                  </span>
                </span>
              </a>
            </td>
            <td>
              <a href="#">
                <span class="glyphicon glyphicon-plus-sign">
                </span>
              </a>
            </td>
            <td class="word-no-<%= word.id %>"><a href="#" class="translate"><span class="glyphicon glyphicon-refresh"></span></a></td>
          </tr>

          <tr class="hide-text word-id-<%= word.id %> language-id-<%= word.language_id %>">
            <td class="word-no-<%= word.id %>">
              <% lang = current_user.targettongue_id %>
              <% lang = Language.find(lang) %>
              <% lang = lang.language %>
              <%= link_to word.french, lang %>
            </td>
            <td><a href="#"><span class="glyphicon glyphicon-play-circle"></span></a></td>
            <td><a href="#"><span class="glyphicon glyphicon-plus-sign"></span></a></td>
            <td class="word-no-<%= word.id %>"><a href="#"><span class="glyphicon glyphicon-refresh"></span></a></td>
          </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to 'New Word', new_category_word_path(@category), class: 'btn btn-success' %>
  </div>
</div>

app/views/words/new.html.erb
<h1>New word</h1>

<%= render 'form' %>

<%= link_to 'Back', new_category_word_path(@category) %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Word:</b>
  <%= @word.word %>
</p>

<p>
  <b>Spanish:</b>
  <%= @word.spanish %>
</p>

<p>
  <b>French:</b>
  <%= @word.french %>
</p>

<p>
  <b>German:</b>
  <%= @word.german %>
</p>

<p>
  <b>Mandarin:</b>
  <%= @word.mandarin %>
</p>

<p>
  <b>Arabic:</b>
  <%= @word.arabic %>
</p>

<p>
  <b>German:</b>
  <%= @word.russian %>
</p>


<p>
  <b>Categories:</b>
  <% if @word.categories.any? %>
  	<% @word.categories.each do |category| %>
  		<%= category.category %><br />
  	<% end %>
  <% end %>
</p>


<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>